# Generated by Django 2.1.5 on 2019-02-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='discription',
            new_name='description',
        ),
    ]
