# Generated by Django 2.1.5 on 2019-02-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190203_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('자격증', '자격증'), ('교내활동', '교내활동'), ('교외활동', '교외활동')], default=True, max_length=10),
        ),
    ]
